### ISSUE TITLE
client.create_document_from_template doesnt support sandbox mode

### ISSUE THREAD

**Issue by lidorkook** [eversign/eversign-python-sdk#10]
It seems that the sandbox param is not in the data that is sent to the request post.
https://github.com/eversign/eversign-python-sdk/blob/master/eversign/client.py

**Comment by milanlatinovic** [comment]
@lidorkook you can enable sandbox when creating documents with ```document.sandbox = True```
You can examine example create_document.py

This will result in a created document that has a title with the prefix "[test-only-not-binding]".
I have tested this functionality with the current master and it works.

Please let us know if your use case is different in any way.
We have introduced Issue templates so you can describe detailed issue with code examples and any additional explanation.

For now, I will close this issue.
