### ISSUE TITLE
API Requests

### ISSUE THREAD

**Issue by CristopherSazon** [eversign/eversign-python-sdk#20]
1. Creating a document doesn't return the field "embedded_claim_url", can we include it in Document model, please?
2. Can I request if we can have an endpoint where it return the s3 url of the signed document, we have a feature in our site where we want to show/embed the document just for viewing

Thank you!

**Comment by milanlatinovic** [comment]
Hi @CristopherSazon,

Thanks for mentioning this, it is appreciated.

1. I will extend document model with "embedded_claim_url" and make a new release. Please, keep in mind that embedded_claim_url is appearing only when you are creating document as a draft, meaning when you use `is_draft = True`. In all other cases, document will be already created and there is nothing to embed. 

2. Currently we are not at the level of supporting dedicated s3 endpoints. However, this is an open SDK, so if you want to extend it with this feature, you can do that and create a pull request, which can be approved and merged to our codebase. You can examine our API documentation for features related to getting a document, https://eversign.com/api/documentation/methods#get-document-template

I will work on items from point 1 and let you know as soon as we have new release. :)

**Comment by milanlatinovic** [comment]
Hi again @CristopherSazon,

I made promised changes and published new package here https://pypi.org/project/eversign/1.2.3/#history
Will mark this issue as resolved now.

Related to item 2, if you make a working code and merge request, please add me and I will review it. :)

Also, you can follow up on hashtag #eversign on Twitter and LinkedIn to be informed about latest changes and releases.

Cheers,
Milan
