### ISSUE TITLE
Hidden Tags support

### ISSUE THREAD

**Issue by gwajntrob** [eversign/eversign-python-sdk#22]
Hidden Tags are great, I really need the SDK to support this feature.

Simply add use_hidden_tags to the DocumentModel.

**Comment by milanlatinovic** [comment]
Hi @gwajntrob , thanks for pointing this out and contributing.

I released new SDK version and published PyPI package as well.
https://pypi.org/project/eversign/1.3.0/#history.

Thanks and stay safe,
Milan

**Comment by gwajntrob** [comment]
Thanks @milanlatinovic!
