### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by gwajntrob** [eversign/eversign-python-sdk#23]
There is currently no way to specify which language should be used for signing.

Simply add language to SignerModel.

**Comment by milanlatinovic** [comment]
Hi @gwajntrob , thanks for pointing this out and contributing.

I released new SDK version and published PyPI package as well.
https://pypi.org/project/eversign/1.3.0/#history.

Thanks and stay safe,
Milan

**Comment by gwajntrob** [comment]
Thanks @milanlatinovic!
