### ISSUE TITLE
Embedded viewing url

### ISSUE THREAD

**Issue by CristopherSazon** [eversign/eversign-python-sdk#25]
In our web app, we have this feature where we want to show a preview of a file, can i request a feature where it returns a url use for embedded viewing of the file?

Thank you!

**Comment by milanlatinovic** [comment]
Hi Christopher,

Thanks for reaching out. However, eversign API does not support this feature out of the box, which is a reason why it is not in SDK. 

As a workaround you can try to use download_final_document endpoint, https://eversign.com/api/documentation/methods#download-final-pdf and then use this pdf to generate a  preview.

Hopefully this makes sense. 

p.s. I will mention feature proposal to my team in any case, to be added to backlog, refined and prioritized with all other feature proposals.

All best,
Milan
