### ISSUE TITLE
file_url: "Couldn't interpret '/tmp/tmp0qfuxn3n/7ae02578-b9fb-11eb-a93e-0242ac11000a-some_Doc-file.pdf' as string."

### ISSUE THREAD

**Issue by jumasheff** [eversign/eversign-python-sdk#26]
**Describe the bug**

I tried to create a document and downloaded a file from s3 url to a temp dir and passed its path as `file_url`. But File.validate() raised DataError:
`{"file_url": ["Couldn't interpret '/tmp/tmp0qfuxn3n/7ae02578-b9fb-11eb-a93e-0242ac11000a-some_Doc-file.pdf' as string."]}`

**To Reproduce**
1. Code looks like this:
```
        document = eversign.Document()
        document.is_draft = True
        document.title = 'Test'
        document.sandbox = True

        with TemporaryDirectory() as tmpdir:
              file_name = Path(s3_file.name).name
              tmp_path = Path(tmpdir)
              file_path = tmp_path / file_name
              r = requests.get(s3_file.url)
              with open(file_path, 'wb') as f:
                  f.write(r.content)
              doc_file = eversign.File(name=file_name)
              doc_file.file_url = file_path
              document.add_file(doc_file)
...
```
2. See error

**Expected behavior**
Validation passes without issues and document is created successfully

**Screenshots**
<img width="1433" alt="Screen Shot 2021-05-26 at 12 58 50" src="https://user-images.githubusercontent.com/3319967/119616197-24c52f00-be22-11eb-995a-137ac481d8d2.png">

**Comment by jumasheff** [comment]
Forget about this :) I was passing `PosixPath`, not a string.

**Comment by milanlatinovic** [comment]
Thanks for followup @jumasheff , all best!
