### ISSUE TITLE
client.get_completed_documents(): through python to the API - receives internal server error 

### ISSUE THREAD

**Issue by aairhenig** [eversign/eversign-python-sdk#27]
**Describe the bug**
Any time a call is made to client.get_completed_documents(): through python to the API, the following error is received 
    raise EversignException(code, _type, info)
eversign.utils.EversignException: (0, 'internal_server_error', None)

**To Reproduce**
run python the following 
for document in client.get_completed_documents():
      print(document)

**Expected behavior**
error received:

Traceback (most recent call last):
  File "documentssigned.py", line 13, in <module>
    for document in client.get_completed_documents():
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eversign\client.py", line 209, in get_completed_documents
    return self._get_documents('completed')
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eversign\client.py", line 447, in _get_documents
    raise e
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eversign\client.py", line 442, in _get_documents
    return_type=return_type)
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eversign\client.py", line 501, in _request
    raise EversignException(code, _type, info)
eversign.utils.EversignException: (0, 'internal_server_error', None)

**Screenshots**

**Desktop (please complete the following information):**
Windows 10 
Python 3.7.7
eversign API uninstalled and reinstalled today

**Smartphone (please complete the following information):**
Dell

**Comment by milanlatinovic** [comment]
Hi @aairhenig 

I made a quick example to doublecheck if the issue you reported is present.

Here is the code sample I used

```
import sys
import config
from pprint import pprint
sys.path.append("..")
import eversign

client = eversign.Client(config.access_key)

count = 0
for document in client.get_all_documents():
    count+=1

print('Successfully fetched all ' + str(count) + ' documents')

count = 0
for document in client.get_completed_documents():
    count+=1

print('Successfully fetched ' + str(count) + ' completed documents')
```

When I executed this code from my local development I got correct result, without any issues
```
root@...:/opt/sdk# PYTHONPATH=$(pwd) python examples/get_documents.py
Successfully fetched all 312 documents
Successfully fetched 33 completed documents
```

Meaning, atm I do not see anything wrong with SDK code itself.

I would suggest you do some more checks from your side.
If you find some edge case that is causing but for you, please reopen this issue with more details.

Thanks,
Milan

**Comment by aairhenig** [comment]
Hi there @milanlatinovic 

I have run your exact code on three different machines with brand new installs of both python and the SDK. I continue to get the same error.  Its pretty urgent that I be able to print some documents. Thanks! I would hazard a guess that it possibly has to do with the number of documents that the business has? The error looks like it is potentially a time out or data oversize error? 

Is there someone that I can actually speak with to help resolve?

**Comment by milanlatinovic** [comment]
Hi @aairhenig,

Python SDK that we are having here is a wrapper that communicates with eversign API.
`internal_server_error` is being thrown by eversign API and not by the SDK itself.

It is possible that number of documents or payload is what causes the issue.
But this is something that you need to check with eversign API.

My advise is to proceed in this way:
- Try using eversign api to create a request that you need (without using this SDK) just to confirm if you will still get the issue
- If you can not locate the issue, you should create support ticket for eversign and try to see what your account has issues with API

Kind regards,
Milan
